apiVersion: v1
kind: Pod
metadata:
  name: python-lab-test
spec:
  containers:
    - name: python-lab
      image: python-lab
      imagePullPolicy: Never
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: "200m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
  restartPolicy: Never